web_s10195019/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using web_s10195019.Models;

namespace web_s10195019.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public async Task<ActionResult> Index() 
        { 
            HttpClient client = new HttpClient(); 
            client.BaseAddress = new Uri("https://ictonejourney.com"); 
            HttpResponseMessage response = await client.GetAsync("/api/books"); 
            if (response.IsSuccessStatusCode) 
            { 
                string data = await response.Content.ReadAsStringAsync(); 
                List<Book> bookList = JsonConvert.DeserializeObject<List<Book>>(data); 
                return View(bookList); } 
            else 
            { return View(new List<Book>()); 
            } 
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        public async Task<ActionResult> Reserve(int id)
        {
            //Retreive access token 
            string accessToken = await HttpContext.GetTokenAsync("access_token"); 
            HttpClient client = new HttpClient();    
            client.BaseAddress = new Uri("https://ictonejourney.com");    
            //Add the access token to the header  
            client.DefaultRequestHeaders.Authorization =       
                new AuthenticationHeaderValue("Bearer", accessToken);   
            BookReserve br = new BookReserve(id);   
            //Convert the BookReserve object to JSON string   
            string json = JsonConvert.SerializeObject(br);
            StringContent reserveContent = new StringContent(json,                   
                UnicodeEncoding.UTF8, "application/json");   
            //Call Web API to create reserve a selected book    
            HttpResponseMessage response = await client.PostAsync(   
                "/api/books", reserveContent);      
            if (response.IsSuccessStatusCode)     
                TempData["Status"] = "Book Reserved";     
            else        
                TempData["Status"] = "Error Reserving Book";       
            return RedirectToAction(nameof(Index));
        }
    }
}

web_s10195019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NP Book Rental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @if (Context.Session.GetString("Role") != null)
        {
            if (Context.Session.GetString("Role") == "Staff")
            {
                @await Html.PartialAsync("_StaffMenu.cshtml")
            }
            if (Context.Session.GetString("Role") == "Student")
            { 
                @await Html.PartialAsync("_StudentMenu.cshtml")
            }
    }

    </header>
    <!-- Bootstrap container, centralise the container between margins -->
    <div class="container">
        <!-- 1st row -->
        <div class="row">
            <div class="col-sm-12">
                <p style="padding:2px 15px;">
                    @{
                        string userId = "Anonymous";
                        string userRole = "Unknown";
                        string logtime = "Unknown";
                        if (Context.Session.GetString("LoginID") != null)
                        {
                            userId = Context.Session.GetString("LoginID");
                        }
                        if (Context.Session.GetString("Role") != null)
                        {
                            userRole = Context.Session.GetString("Role");
                        }
                        if (Context.Session.GetString("Time") != null)
                        {
                            logtime = Context.Session.GetString("Time");
                        }
                    }
                    Welcome,&nbsp;
                    <span style="font-weight:bold">@userId</span>&nbsp;
                    (Role: @userRole).&nbsp;
                    You have logged in since @logtime.ToUpper()
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top small text-right text-muted">
        <p style-"padding-right:15px; padding-top: 5px">
            WEB Practical  Exercises - &copy;@DateTime.Today.Year
            School of ICT, Ngee Ann Polytechnic
        </p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

web_s10195019/Views/Shared/_StaffMenu.cshtml
<!-- A grey navbar that expands horizontally at medium device -->
<nav class="navbar navbar-expand-md bg-light navbar-light">
    <!-- The brand(or icon) of the navbar -->
    <a class="navbar-brand" href="~/Home/StaffMain" style="font-size:32px; font-weight:bold; color:#3399FF;">
        NP Book Rental
    </a>
    <!-- Toggle/collapsible Button, also known as hamburger button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#staffNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Links in the navbar, displayed as drop-down list when collapsed -->
    <div class="collapse navbar-collapse" id="staffNavbar">
        <!-- Links that are aligned to the left, mr-auto: right margin auto-adjusted -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="~/Rental/Calculate">
                    Rental Calculator
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Fine/Calculate">Fine Calculator</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Staff/Index">View Staff</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/Branch/Index">View Branch</a>
            </li>
        </ul>
        <!-- Links that are aligned to the right, ml-auto: left margin auto-adjusted -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <!-- A link for logging out user -->                 
                <a class="nav-link" href="~/Home/LogOut">Log Out</a>
            </li>
        </ul>
    </div>
</nav>

web_s10195019/Views/Shared/_StudentMenu.cshtml
<!-- A grey navbar that expands horizontally at medium device -->
<nav class="navbar navbar-expand-md bg-light navbar-light">    
    <!-- The brand(or icon) of the navbar -->    
    <a class="navbar-brand" href="~/Book/Index" style="font-size:32px; font-weight:bold; color:#3399FF;">     
    NP Book Rental   
    </a>    
    <!-- Toggle/collapsible Button, also known as hamburger button --> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#studentNavbar">       
        <span class="navbar-toggler-icon"></span>
    </button>     
    <!-- Links in the navbar, displayed as drop-down list when collapsed -->  
    <div class="collapse navbar-collapse" id="studentNavbar">        
    <!-- Links that are aligned to the left,              
        mr-auto: right margin auto-adjusted -->       
        <ul class="navbar-nav mr-auto">           
            <li class="nav-item">             
                <a class="nav-link" asp-controller="Book" asp-action="Index">View Books</a> 
            </li>        
        </ul>       
        <!-- Links that are aligned to the right,              
            ml-auto: left margin auto-adjusted -->        
        <ul class="navbar-nav ml-auto">         
            <li class="nav-item">            
        <   !-- A link for logging out user -->            
            <a class="nav-link" href="~/Home/LogOut">Log Out</a>     
            </li>       
        </ul>     
    </div> 
</nav>