web_s10195019/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace web_s10195019.Models
{
    public class Book
    {
        public string Justification { get; set; }
        [Display(Name = "Book ID")] public int Id { get; set; }
        [Display(Name = "ISBN")] public string Isbn { get; set; }
        [Display(Name = "Title")] public string Title { get; set; }
        [Display(Name = "Author")] public string Author { get; set; }
        [Display(Name = "Pages")] public int Pages { get; set; }
        [Display(Name = "Quantity Available")] public int Qty { get; set; }
    }
    public class BookReserve
    {
        public BookReserve(int id)
        {
            BookId = id;
        }
        public int BookId { get; set; }
    }
}

web_s10195019/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using web_s10195019.Models;

namespace web_s10195019.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public async Task<ActionResult> Index() 
        { 
            HttpClient client = new HttpClient(); 
            client.BaseAddress = new Uri("https://ictonejourney.com"); 
            HttpResponseMessage response = await client.GetAsync("/api/books"); 
            if (response.IsSuccessStatusCode) 
            { 
                string data = await response.Content.ReadAsStringAsync(); 
                List<Book> bookList = JsonConvert.DeserializeObject<List<Book>>(data); 
                return View(bookList); } 
            else 
            { return View(new List<Book>()); 
            } 
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [Authorize]
        public async Task<ActionResult> Reserve(int id)
        {
            //Retreive access token 
            string accessToken = await HttpContext.GetTokenAsync("access_token"); 
            HttpClient client = new HttpClient();    
            client.BaseAddress = new Uri("https://ictonejourney.com");    
            //Add the access token to the header  
            client.DefaultRequestHeaders.Authorization =       
                new AuthenticationHeaderValue("Bearer", accessToken);   
            BookReserve br = new BookReserve(id);   
            //Convert the BookReserve object to JSON string   
            string json = JsonConvert.SerializeObject(br);
            StringContent reserveContent = new StringContent(json,                   
                UnicodeEncoding.UTF8, "application/json");   
            //Call Web API to create reserve a selected book    
            HttpResponseMessage response = await client.PostAsync(   
                "/api/books", reserveContent);      
            if (response.IsSuccessStatusCode)     
                TempData["Status"] = "Book Reserved";     
            else        
                TempData["Status"] = "Error Reserving Book";       
            return RedirectToAction(nameof(Index));
        }
    }
}

web_s10195019/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using web_s10195019.Models;

namespace web_s10195019.Controllers
{
    public class VoteController : Controller
    {
        // GET: VoteController
        public ActionResult Index()
        {
            return View();
        }

        // GET: VoteController/Details/5
        public async Task<ActionResult> Details(int id)
        {    
            // Make Web API call to get a list of votes related to a BookId   
            HttpClient client = new HttpClient();   
            client.BaseAddress = new Uri("https://ictonejourney.com");    
            HttpResponseMessage response = await                      
                client.GetAsync("/api/votes/" + id.ToString());       
            if (response.IsSuccessStatusCode) 
            {       
                string data = await response.Content.ReadAsStringAsync(); 
                List<VoteDetails> voteList =            
                    JsonConvert.DeserializeObject<List<VoteDetails>>(data);     
                return View(voteList);  
            }     
            else
            {     
                return View(new List<VoteDetails>());  
            } 
        }

            // GET: VoteController/Create
            public ActionResult Create()
        {
            return View();
        }

        // POST: VoteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {     
            // Read BookId and Justification from HTML Form   
            int bookid = Convert.ToInt32(collection["item.Id"]);   
            string justification = collection["item.Justification"];       
            // Transfer data read to a vote object    
            Vote vote = new Vote();    
            vote.BookId = bookid; 
            vote.Justification = justification;    
            // Make Web API call to post the vote object        
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://ictonejourney.com"); 

            //Convert the vote to JSON string    
            string json = JsonConvert.SerializeObject(vote);   
            StringContent votecontent = new StringContent(json, UnicodeEncoding.UTF8, "application/json"); 
            HttpResponseMessage response = await client.PostAsync("/api/votes", votecontent); 

            if (response.StatusCode == HttpStatusCode.Created)
            {         
                // Successful – code 201 returned   
                return RedirectToAction("Details", new { id = bookid });    
            }   
            else 
            {       
                // Unsuccessful – other returned code       
                TempData["BookId"] = bookid;    
                TempData["Justification"] = justification;    
                TempData["Message"] = "Fail to add vote record!";     
                return RedirectToAction("Index", "Book");    
            } 
        }

                // GET: VoteController/Edit/5
                public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VoteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VoteController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VoteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

web_s10195019/Views/Book/Index.cshtml
@model IEnumerable<web_s10195019.Models.Book>

@{
    ViewData["Title"] = "View Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="PageTitle">View Books</h4>

@if (Model.ToList().Count > 0)
{
    string status = "";
    if (TempData["Status"]!=null)
    {
        status = TempData["Status"].ToString();
    }
    <div class="table-responsive">    
        <span style="color:red;">@status</span>
        <table id="viewBook" class="table table-striped table-bordered">      
            <thead class="thead-dark">          
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@Html.DisplayNameFor(model => model.Isbn)</th>
                    <th>@Html.DisplayNameFor(model => model.Title)</th>
                    <th>@Html.DisplayNameFor(model => model.Author)</th>
                    <th>@Html.DisplayNameFor(model => model.Pages)</th>
                    <th>@Html.DisplayNameFor(model => model.Qty)</th>
                    <th>Justification</th>
                    <th>Reserve Book</th>
                </tr>       
            </thead>        
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>                         
                        <td>@item.Id</td>       
                        <td>@item.Isbn</td>      
                        <td>@item.Title</td>         
                        <td>@item.Author</td>         
                        <td>@item.Pages</td>             
                        <td>@item.Qty</td>    
                        <td>         
                            @{ 
                                int rBookId; 
                                string rJustification = "", errorMsg = "";            
                                // An error for the row detected            
                                if (TempData["BookId"] != null) {                
                                    rBookId = Convert.ToInt32(TempData["BookId"]); 
                                    if (rBookId == item.Id) {                    
                                        rJustification = TempData["Justification"].ToString();       
                                        errorMsg = @TempData["Message"].ToString();               
                                    }        
                                }         
                            }       
                            <form asp-controller="Vote" asp-action="Create" method="post">   
                                <table>              
                                    <tr>           
                                        <td>                 
                                            <input asp-for="@item.Justification"  
                                                   value="@rJustification" />        
                                            <input type="hidden" asp-for="@item.Id" /> 
                                            <input type="submit" value="Add"    
                                                   class="btn btn-primary" />      
                                            <span style="color:red;">@errorMsg</span>     
                                        </td>   
                                    </tr>         
                                </table>       
                            </form> 
                        </td>
                        <td>
                            @if (item.Qty > 0)
                            {
                                <a asp-action="Reserve" asp-controller="Book" asp-route-id="@item.Id">Reserve</a>
                            }
                        </td>
                    </tr>

                }         
            </tbody>        
        </table>  
    </div>
}
else
{ 
    <span style="color:red">No record found!</span>
    }