web_s10195019/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_s10195019.Models
{
    public class Branch
    {
        [Display(Name = "ID")]
        public int BranchNo { get; set; }

        public string Address { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"[689]\d{7}|\+65[689]\d{7}$", ErrorMessage = "Invalid Singapore Phone Number")]
        public string Telephone { get; set; }
        
        
    }
}

web_s10195019/Models/BranchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace web_s10195019.Models
{
    public class BranchViewModel
    {
        public List<Branch> branchList { get; set; }
        public List<Staff> staffList { get; set; }
        public BranchViewModel()
        { 
            branchList = new List<Branch>(); 
            staffList = new List<Staff>(); 
        }
    }
}

web_s10195019/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_s10195019.DAL;
using web_s10195019.Models;

namespace web_s10195019.Controllers
{
    public class BranchController : Controller
    {
        private BranchDAL branchContext = new BranchDAL();

        // GET: Branch
        public ActionResult Index(int? id)
        {
            // Stop accessing the action if not logged in        
            // or account not in the "Staff" role           
            if ((HttpContext.Session.GetString("Role") == null) || 
                (HttpContext.Session.GetString("Role") != "Staff"))          
            {                
                return RedirectToAction("Index", "Home");           
            } 

            BranchViewModel branchVM = new BranchViewModel();
            branchVM.branchList = branchContext.GetAllBranches();         
            // BranchNo (id) present in the query string      
            if (id != null)           
            {                 
                ViewData["selectedBranchNo"] = id.Value;    
                branchVM.staffList = branchContext.GetBranchStaff(id.Value);   
            }          
            else           
            {          
                ViewData["selectedBranchNo"] = "";     
            }             
            return View(branchVM);
        }

        // GET: BranchController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BranchController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BranchController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BranchController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BranchController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BranchController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BranchController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

web_s10195019/Views/Branch/Branch.cshtml
@model web_s10195019.Models.BranchViewModel

@{ ViewData["Title"] = "View Branch"; }

<h4 class="PageTitle">View Branch</h4>
<!-- Display a list of branches -->
<div class="table-responsive">
    <table id="viewBranch" class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Telephone</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.branchList)
            {
                string selectedRow = "";
                if (ViewData["selectedBranchNo"].ToString() == item.BranchNo.ToString())
                {
                    // Highlight the selected row
                    selectedRow = "class='table-primary'";
                }
                <tr @Html.Raw(selectedRow)>
                    <td>@item.BranchNo.ToString()</td>
                    <td>@item.Address</td>
                    <td>@item.Telephone</td>
                    <td>
                        <a asp-action="Index" asp-controller="Branch" asp-route-id="@item.BranchNo">View Staff</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Display a list of staff members for each branch -->
@if (ViewData["selectedBranchNo"].ToString() != "")
{
    if (Model.staffList.Count != 0)
    {
        <h5>
            Staff working in Branch
            @ViewData["selectedBranchNo"].ToString() :
        </h5>
        <partial name="~/Views/Staff/_ViewStaff.cshtml" model="@Model.staffList" />
    }
    else
    {
        <h5>No staff for selected branch!</h5>
    }

 }